### ISSUE TITLE
Todo list: Engine

### ISSUE THREAD

**Issue by tioover** [tioover/sansa#4]
- [x] <del>remake</del> refactor animation module
- [x] remove unnecessary `Vec2<T>`
- [x] camera animation
- [x] shader refactor
- [ ] UI
- [ ] vector drawing
- [x] a name: Erya
- [x] split into a new repository: [here](https://github.com/ruoruo-dev/erya)

**Comment by tioover** [comment]
move to https://github.com/ruoruo-dev/erya
